import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	drop: prod ? ["console", "debugger"] : [],
});

if (prod) {
	await context.rebuild();
	copyFileSync(
		"node_modules/mediainfo.js/dist/MediaInfoModule.wasm",
		"MediaInfoModule.wasm"
	);
	process.exit(0);
} else {
	// Copy WASM for dev mode too
	copyFileSync(
		"node_modules/mediainfo.js/dist/MediaInfoModule.wasm",
		"MediaInfoModule.wasm"
	);
	await context.watch();
}
