name: CI

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 22.x
              uses: actions/setup-node@v5
              with:
                  node-version: 22.x
                  cache: "npm"
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm test
            - name: Verify WASM file exists
              run: test -f MediaInfoModule.wasm
